server:
  port: 8080

spring:
  cloud:
    function:
      definition: consumeServiceBusMessage

    azure:
      servicebus:
        connection-string: ${SERVICEBUS_CONNECTION_STRING}

    stream:
      default-binder: servicebus
      binders:
        servicebus:
          type: servicebus
          environment:
            spring:
              cloud:
                azure:
                  servicebus:
                    connection-string: ${SERVICEBUS_CONNECTION_STRING}
      bindings:
        consumeServiceBusMessage-in-0:
          destination: ${SERVICEBUS_QUEUE_NAME}
          content-type: application/json
          consumer:
            auto-complete: false

logging:
  level:
    org.springframework.cloud.stream: DEBUG
    com.azure.spring.integration: DEBUG
