spring:
  cloud:
    azure:
      eventhubs:
        connection-string: ${EVENTHUBS_CONNECTION_STRING}
      servicebus:
        connection-string: ${SERVICEBUS_CONNECTION_STRING}
    stream:
      bindings:
        consume-in-0:
          destination: ${EVENTHUBS_NAME}
        consumeServiceBusMessage-in-0:
          destination: ${SERVICEBUS_QUEUE_NAME}
      eventhubs:
        bindings:
          consume-in-0:
            consumer:
              checkpoint-storage-account: ${CHECKPOINT_STORAGE_ACCOUNT}
              checkpoint-container: ${CHECKPOINT_CONTAINER}
